### PR TITLE
Adding support for material-ui-next

### PR DESCRIPTION
**Pull request by lucianobustos**
These minor corrections allows you to work with the latest version of https://material-ui-next.com/

**Here you can see the component**
image

### CODE REVIEW

**Comment by lucianobustos** [comment]
@lo-tp could you help me to understand/fix travies build failure.? I think is a minor thing. Rigth?

**Comment by lo-tp** [comment]
@lucianobustos 
Sure.
I'll help you fix the test.

I want hear you idea about a dedicated repo for material-ui-next.
I think a dedicated repo should help a lot in the maintenance perspective.

**Comment by lucianobustos** [comment]
Yes I think I dedicated robot is OK for that just create that one and I will follow you

Enviado desde mi Apple Watch

**Comment by lo-tp** [comment]
@lucianobustos to fix the build problem, you are supposed to change third line of `src/index.jsx`
from `import Button from 'material-ui/Button';` to `import Button from 'material-ui/FlatButton';`

However,  some new problems arise when running the unit test which have to be resolved before we can proceed.

**Pull request closed without merging**
